[2025-03-30T10:39:43.906+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T10:39:43.944+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aqi_etl_pipeline.validate_aqi_data_Nonthaburi manual__2025-03-30T10:39:26.348292+00:00 [queued]>
[2025-03-30T10:39:43.962+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aqi_etl_pipeline.validate_aqi_data_Nonthaburi manual__2025-03-30T10:39:26.348292+00:00 [queued]>
[2025-03-30T10:39:43.962+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-30T10:39:44.014+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): validate_aqi_data_Nonthaburi> on 2025-03-30 10:39:26.348292+00:00
[2025-03-30T10:39:44.060+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=53093) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T10:39:44.061+0000] {standard_task_runner.py:72} INFO - Started process 53152 to run task
[2025-03-30T10:39:44.086+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'aqi_etl_pipeline', 'validate_aqi_data_Nonthaburi', 'manual__2025-03-30T10:39:26.348292+00:00', '--job-id', '509', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmpwnwaobib']
[2025-03-30T10:39:44.105+0000] {standard_task_runner.py:105} INFO - Job 509: Subtask validate_aqi_data_Nonthaburi
[2025-03-30T10:39:44.448+0000] {task_command.py:467} INFO - Running <TaskInstance: aqi_etl_pipeline.validate_aqi_data_Nonthaburi manual__2025-03-30T10:39:26.348292+00:00 [running]> on host 58b9640d9ecf
[2025-03-30T10:39:44.941+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='validate_aqi_data_Nonthaburi' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T10:39:26.348292+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T10:39:26.348292+00:00'
[2025-03-30T10:39:44.948+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-30T10:39:44.952+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-30T10:39:44.952+0000] {logging_mixin.py:190} INFO - Current task name:validate_aqi_data_Nonthaburi state:running start_date:2025-03-30 10:39:43.945840+00:00
[2025-03-30T10:39:44.953+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline and current dag run status:running
[2025-03-30T10:39:44.956+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-30T10:39:44.957+0000] {logging_mixin.py:190} INFO - ✅ Validating data for Nonthaburi: {
  "status": "fail",
  "data": {
    "message": "Too Many Requests"
  }
}
[2025-03-30T10:39:44.957+0000] {logging_mixin.py:190} INFO - ❌ Value Error in Nonthaburi: Error: Too Many Requests for city Nonthaburi.
[2025-03-30T10:39:44.959+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 89, in _validate_aqi_data
    raise ValueError(f"Error: {message} for city {city}.")
ValueError: Error: Too Many Requests for city Nonthaburi.
[2025-03-30T10:39:44.994+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-30T10:39:45.003+0000] {logging_mixin.py:190} INFO - Task start:2025-03-30 10:39:43.945840+00:00 end:2025-03-30 10:39:44.994197+00:00 duration:1.048357
[2025-03-30T10:39:45.003+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): validate_aqi_data_Nonthaburi> dag:<DAG: aqi_etl_pipeline> dagrun:<DagRun aqi_etl_pipeline @ 2025-03-30 10:39:26.348292+00:00: manual__2025-03-30T10:39:26.348292+00:00, state:running, queued_at: 2025-03-30 10:39:26.372196+00:00. externally triggered: True>
[2025-03-30T10:39:45.004+0000] {logging_mixin.py:190} INFO - Failure caused by Error: Too Many Requests for city Nonthaburi.
[2025-03-30T10:39:45.004+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=aqi_etl_pipeline, task_id=validate_aqi_data_Nonthaburi, run_id=manual__2025-03-30T10:39:26.348292+00:00, execution_date=20250330T103926, start_date=20250330T103943, end_date=20250330T103944
[2025-03-30T10:39:45.055+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-30T10:39:45.056+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 509 for task validate_aqi_data_Nonthaburi (Error: Too Many Requests for city Nonthaburi.; 53152)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 89, in _validate_aqi_data
    raise ValueError(f"Error: {message} for city {city}.")
ValueError: Error: Too Many Requests for city Nonthaburi.
[2025-03-30T10:39:45.147+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T10:39:45.264+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T10:39:45.312+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
